### ISSUE TITLE
Trying to open the add-on preferences or closing Anki with the add-on installed gives an error

### ISSUE THREAD

**Issue by Voxtopass** [RisingOrange/Reset-Ease-Automatically#4]
I've tried enabling/re-enabling and reinstalling.

Here's the debug info:

Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-12 16:58:04

Caught exception:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\12081346\preferences_dialog.py", line 204, in show
    mw.mm = PreferencesDialog(mw.app.activeWindow())
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\12081346\preferences_dialog.py", line 22, in __init__
    clean_up_deck_to_ease()
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\12081346\utils.py", line 9, in clean_up_deck_to_ease
    convert_deck_names_to_ids_in_deck_to_ease()
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\12081346\utils.py", line 25, in convert_deck_names_to_ids_in_deck_to_ease
    for deck_name_or_id, ease in get_value('deck_to_ease').items()
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by RisingOrange** [comment]
I just uploaded an update to the addon. Does it fix the problem?

**Comment by Voxtopass** [comment]
Yes, that fixed it. Thank you!

**Comment by Voxtopass** [comment]
Actually, trying to save my preferences now gives this:

Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-12 16:58:04

Caught exception:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\12081346\preferences_dialog.py", line 122, in _on_down
    self._move_row_up(row_idx + 1)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\12081346\preferences_dialog.py", line 189, in _move_row_up
    if not 0 < row_idx < len(self._table_rows()):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\12081346\preferences_dialog.py", line 148, in _table_rows
    return [
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\12081346\preferences_dialog.py", line 149, in <listcomp>
    table_view_row_to_data_row(table_view_row_at_idx(row_idx))
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\12081346\preferences_dialog.py", line 138, in table_view_row_to_data_row
    result['Deck'] = mw.col.decks.id_for_name(model_row[0].currentText())
AttributeError: 'DeckManager' object has no attribute 'id_for_name'

**Comment by RisingOrange** [comment]
Could you please verify if it works now?

**Comment by Voxtopass** [comment]
That did it. Now everything works. Thank you for the added compatibility. A lot of people in the MIA community stay on certain Anki versions for other add-ons, so that will probably be helpful.
